### PR TITLE
(Feature) Adds function to change color of data-encoded svg-icons

### PR DESCRIPTION
**Pull request by KasperAndersson**
See it in action [here](https://codepen.io/KasperAndersson/pen/JwpVmm)

### CODE REVIEW

**Review by slavanga — CHANGES_REQUESTED** [review]
Thank you for this PR.
I like the idea but there is some work to do before I can merge it 😉

- The version number will be changed before a new release. Please don't change it in a feature commit.
- Remove the .cion-red class from baseguide.css
- Add a !default flag to the ```$icons``` map in the settings.
- Rename the variable ```$icon-default-color``` to just ```$icon-color```
- The value for the setting ```$icon-color``` should be a normal hex color (#333).
- The default value for the ```$color``` parameter in the get-icon function should be ```$icon-color```
- Use silent comments for the usage example. It should not appear in the compiled CSS. The example should be very simple and easy to understand. See my take on it below.
- The error message in get-icon should be: "Please make **sure** '#{$icon}' is defined in **the** `$icons` map."
- There is no need to return null after the errors as the compilation is stopped anyway.
- Update the icons in _form-custom.scss to use the new function: e.g. url(get-icon('select'))
- Run ```gulp lint``` to autoformat the scss code.

```scss
// Usage example:
//
// .icon {
//   background-image: url(get-icon('radio', '#fff'));
// }
```

**Review by slavanga — APPROVED** [review]

**Review by slavanga — CHANGES_REQUESTED** [review]
Nice, if you fix the fill of the svg icons I will merge this feature.

**Comment by KasperAndersson** [comment]
Sorry, didn't see the error in compiled CSS - will need to look into this.

**Review by slavanga — APPROVED** [review]

**Comment by slavanga** [comment]
Merged 🎉

**Pull request merged**
